### ISSUE TITLE
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/designer#100]
Tried to test the new version, started with

```
bower install
npm install
npm start
```
Opened ` localhost:8080/` in canary, but only got
![2015-04-01_1705](https://cloud.githubusercontent.com/assets/7462342/6952563/d669a8fe-d890-11e4-935d-8a1c9f1e69aa.png)

![2015-04-01_1723](https://cloud.githubusercontent.com/assets/7462342/6952861/8183dea6-d893-11e4-96e3-4b520e9db30c.png)

**Comment by justinfagnani** [comment]
I'll take a look on a fresh repo, but first, did you build the project? `npm run-script build`

**Comment by IntranetFactory** [comment]
I didn't not execute `npm run-script build` before. Is this needed?

When trying it fails as well

![2015-04-01_1727](https://cloud.githubusercontent.com/assets/7462342/6952942/0a2d93aa-d894-11e4-9cc9-c21165466a03.png)

**Comment by justinfagnani** [comment]
I updated the README to include the build instructions in the Development section.

**Comment by justinfagnani** [comment]
I see you're on Windows. I'm not sure what we have to do to get the build to work on there. I'll file an issue.

**Comment by IntranetFactory** [comment]
Is the build step required. Would including the result in the repo be an option? Can't wait to see the new designer. Seeing all the server side dependencies makes me really concerned. The old designer was  server agnostic - which was a big plus from my point of view.

**Comment by justinfagnani** [comment]
We certainly could include the built artifacts, but it's so early right now that it's almost not worth the trouble. The new version really does very little at the moment.

As for the server dependencies, they're also partially for development ease - we need to build up some files for injection into an iframe and the server does this on the fly, enabling edit-refresh for these scripts. That will eventually not be necessary.

We still have an optional server for accessing local files - something Designer 1 couldn't do.

**Comment by IntranetFactory** [comment]
I executed now `npm install browserify -g`. After that I was able to execute `build.sh` without an error. Is this sufficient to build what ever is missing?

**Comment by justinfagnani** [comment]
It should be!

**Comment by IntranetFactory** [comment]
But unfortunately didn't change anything. Just requesting `http://localhost:8080/components/imd/imd.html` already leads to endless redirects. Is that the correct url? I'm wondering because in the files system components reside in bower_components and components ...

**Comment by justinfagnani** [comment]
I just tried in a fresh checkout and it works for me. The main URL would just be `localhost:8080/` but `http://localhost:8080/components/imd/imd.html` works and loads that module fine.

**Comment by IntranetFactory** [comment]
Interesting. What component could then cause the endless redirects I face. When requesting ` http://localhost:8080/components/imd/imd.html` the final url before canary stops becomes `http://localhost:8080/components/imd/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/`

**Comment by justinfagnani** [comment]
Sounds like it could be an issue with polyserve on Windows. https://github.com/PolymerLabs/polyserve

**Comment by justinfagnani** [comment]
Well... neither polyserve or Designer's server.js should be sending any redirects. That's very odd.

**Comment by IntranetFactory** [comment]
I've written code for node - so unfortunately I've no idea how to debug polyserve. Might the different path separators \ / cause any problems e.g. https://github.com/PolymerLabs/polyserve/blob/master/src/server.js#L42

**Comment by justinfagnani** [comment]
I tried to write that in a platform agnostic way. Even if the paths were an issue, I don't see what would be sending a redirect. Can you look at the response headers?

**Comment by IntranetFactory** [comment]
I think the problem is in https://github.com/PolymerLabs/polyserve/blob/master/src/server.js#L42 - it should be  var splitPath = url.pathname.split("/").slice(1); 

Using the windows path separator \ to split the Url probably doesn't work.

**Comment by justinfagnani** [comment]
ah, yes.

**Comment by IntranetFactory** [comment]
Ok, I now got a page showing up. Is that just a prototype? Any roadmap or mockups you can share?

Will the new designer become similar to the old one just working with 0.8 - or something different, more a tool to share prototypes, a kind of polymer aware JSBin?

**Comment by justinfagnani** [comment]
The new tool will eventually be more full-featured than the current Designer. Much more than the old version ported to Polymer 0.8.

First though, we've had to work on a lot of plumbing and security pieces, mainly that the document being edited has to be isolated in a sandboxed iframe so that we can safely run the script that implements elements. Also we want full template editing which Designer 1 lacked.

We'll get design docs and maybe a rough roadmap out this quarter. Right now there's a bunch of obvious stuff just to get some parity with Designer 1: a widget pallet, basic property editing, and some kind of file I/O.

**Comment by IntranetFactory** [comment]
Thank you for the feedback. I'm happy to read that feature parity with Designer1 is a goal. The designer is quite important for our own road map. So I'd be happy to provide ideas, feedback and test. 

Our requirements for the designer are especially "mobile first" (so have a canvas sized/resized to device sizes) and to integrate it with our own backend. We've implemented both already for Designer1 - so I can share information about that as well, if it might be beneficial.

**Comment by justinfagnani** [comment]
That would be _very_ beneficial! It's a good time to design Designer to be modular for these use cases. If you can share a doc with me I'd really appreciate it.

**Comment by IntranetFactory** [comment]
What's the best/suggested place/tool to share this?

**Comment by justinfagnani** [comment]
Google Docs, a repo with markdown, and email are probably the easiest for me.

**Comment by IntranetFactory** [comment]
I've never really used Google Docs. I personally still prefer email (maybe you send me your to martin.amm@adenin.com), but we can also use either this repo or "our" repo with the mobile first version (https://github.com/TangereJs/designer)

**Comment by IntranetFactory** [comment]
This error is gone, but still doesn't work on Windows :-(   See https://github.com/Polymer/designer/issues/135
