### ISSUE TITLE
Cannot set property 'multi' of undefined

### ISSUE THREAD

**Issue by Rich17** [Polymer/designer#112]
Thanks for building the new designer!

Attempted to clone & launch designer 0.8 and received the following error in the console: "Cannot set property 'multi' of undefined" on line 175 of core-selector.html

Equipment used:
OS: Yosemite 10.10.2
Browser: Chrome Canary

Process:
git clone https://github.com/Polymer/designer.git 
cd into project directory
bower install (no errors thrown)
npm install (no errors thrown)
npm run-script build (no errors thrown)
npm start (no errors thrown)
Navigate to localhost:8080 on Chrome Canary. 

Result: Empty (white) screen on browser, with error "Cannot set property of multi of undefined" shown in console

Let me know if you need more information from me - happy to help fix this.

**Comment by justinfagnani** [comment]
Taking a look at this now.

**Comment by justinfagnani** [comment]
Looks like many of the 0.8-preview core-* elements do not work with the latest Polymer 0.8 (with Behaviors). Until `paper-tabs` and `core-pages` are ported over, we're a little dead in the water.

@cdata will hopefully let us know when it's safe to come outside again :)

**Comment by Rich17** [comment]
Ah, okay. Thank you.

**Comment by justinfagnani** [comment]
This should be fixed now
