### ISSUE TITLE
Time Schedule and https://polymer-designer.appspot.com/

### ISSUE THREAD

**Issue by jogibear9988** [Polymer/designer#140]
Is there a Time Scheudle when there will be a first workable Version?

And will the Designer @ https://polymer-designer.appspot.com/ also be updated?

**Comment by justinfagnani** [comment]
There's no schedule, we're working on it fast now that 1.0 is out. The site will be updated when there's a new working version.

**Comment by jogibear9988** [comment]
Thanks 👍🏿

**Comment by jogibear9988** [comment]
Any News???

**Comment by justinfagnani** [comment]
Nope
