### ISSUE TITLE
github token

### ISSUE THREAD

**Issue by macbroadcast** [Polymer/designer#145]
hey there,
since cannary isnt available for linux, i like to play around with the designer on appspot, but i am not
sure about the auth token i need for saving the work, can i use a personal access token or do i need to register a new application in order to save stuff on appspot ?
Thanks :blush:

**Comment by justinfagnani** [comment]
We've removed github support from the deployed version as there were security concerns.

**Comment by mielech** [comment]
and? how to preview using the designer?

**Comment by zaphead** [comment]
Same. I don't know how to preview the components.  :(
