### ISSUE TITLE
Polymer 1.0?

### ISSUE THREAD

**Issue by SilverPaladin** [Polymer/designer#153]
This tool does not create Polymer 1.0 elements. Any plans for 1.0 support?

**Comment by justinfagnani** [comment]
very much, yes.

**Comment by TylorS** [comment]
+1

**Comment by IntranetFactory** [comment]
Any update on the ETA for a designer for Polymer 1.0 ?

**Comment by aabluedragon** [comment]
+1

**Comment by antono** [comment]
+1

**Comment by beast** [comment]
+1

**Comment by mibamur** [comment]
Polymer 1 Roadmap please to README.md
can we help in it or smth else?

**Comment by justinfagnani** [comment]
The roadmap is to bring Designer 2 to feature parity with Designer 1. We've all been extremely with getting Polymer 1.0 released and other important tools. We don't have a timeline, but care very deeply about getting Designer 2 to a usable state.

**Comment by kaushik89ankit** [comment]
+1

**Comment by Colstuwjx** [comment]
+ 1

**Comment by caraya** [comment]
@justinfagnani How can we help get this project to parity with 1.0?

**Comment by SilverPaladin** [comment]
It seems that Polymer as a technology is just too fast moving to bother putting together a tool like designer. Designer 2.0 is not even finished, and the Polymer Project has already advanced to Version 2.0. So this tool would need to be rewritten again just to make it work with Polymer 2.0.

**Comment by justinfagnani** [comment]
Designer 2 didn't quite get to the state where it was editing Polymer elements anyway. It started being able to edit HTML files, then it left off at editing templates. I recently did update Designer itself to use Polymer 2.

The problem isn't that Polymer is moving too fast, it's that we haven't had the resources to dedicate to Designer. I think this will change very soon.

**Comment by SilverPaladin** [comment]
This would be a killer app, I am thinking we could potentially prototype and build at the same time!

**Comment by SilverPaladin** [comment]
Looks like this is going to happen. In the meantime we can use https://github.com/PolymerLabs/wizzywid and look forward to the new designer which will support Polymer 3
