### ISSUE TITLE
Problem running the designer tool

### ISSUE THREAD

**Issue by prateekjadhwani** [Polymer/designer#217]
Hi There,

I am facing some difficulties in running the designer tool. I know that the project is dead, but any help is appreciated.

On the browser I am getting these errors

![image](https://cloud.githubusercontent.com/assets/2219900/16895238/2de3d3b8-4b3e-11e6-9ec5-82c90eb887f6.png)

If anyone could guide me on how to solve this problem that would be great.
I have a cloud9 server running for this on http://designer-tool-prateekjadhwani.c9users.io:8080/

The workspace address is https://ide.c9.io/prateekjadhwani/designer-tool . If you would like to get access to it, please let me know. I am just trying to make it run properly.

Thanks

**Comment by nelsonsilva** [comment]
Try IMD#1.0

**Comment by prateekjadhwani** [comment]
Thank you, it works fine now.
