### ISSUE TITLE
Easy property linking

### ISSUE THREAD

**Issue by techniq** [Polymer/designer#32]
When linking a property to another component's property, it would be useful if after selecting the component to link, if a list of exposed properties on the selected component were available as a dropdown.  I'm just getting into webcomponents/polymer, and I don't believe all "available" are required to be exposed, so I image the dropdown would also need to require text entry still.

![polymer_google_map_properties](https://cloud.githubusercontent.com/assets/177476/3301871/a2ea9572-f62f-11e3-9a76-b37face1894f.png)

**Comment by techniq** [comment]
wontfix :(

**Comment by justinfagnani** [comment]
Not for the old version of designer. I'm sure we'll have nice property selectors in the new version, but it's easier for me to close all old issues right now.

**Comment by techniq** [comment]
:+1
