### ISSUE TITLE
paper-input validate property

### ISSUE THREAD

**Issue by zeleration** [Polymer/designer#41]
The version of Polymer Designer shown at IO demoed a validate property on the paper-input tag, we downloaded the github repo here and made sure it was up to date but the validate property is not shown for the paper-input tag. Any ideas why they are different? TIA.

**Comment by johnlim** [comment]
The validate box is also not shown at https://polymer-designer.appspot.com/

**Comment by robdodson** [comment]
The designer at polymer-designer.appspot.com is pretty much deprecated at this point :\

**Comment by johnlim** [comment]
@robdodson Thanks for clarifying :)
