### ISSUE TITLE
<template repeat... content gets lost

### ISSUE THREAD

**Issue by novascreen** [Polymer/designer#45]
When i switch to code view and write something like this:

    <template repeat="{{m in markers}}">
      <google-map-marker latitude="{{m.latitude}}" longitude="{{m.longitude}}"></google-map-marker>
    </template>

and then switch to design mode and back, the `<google-map-marker>` is gone, basically everything in the `<template>` tag, no matter what markup i put there

i tried this on Chrome 35 on the polymer-project website and in Canary (38) running locally

**Comment by DominicBoettger** [comment]
This also doesn't work:
<template if="{{!rightDrawer}}">
  <core-icon-button id="menuButton" icon="menu" on-tap="{{togglePanel}}"></core-icon-button>
</template>

It's replaced with:

<template if="{{!rightDrawer}}"></template>
<core-icon-button id="menuButton" icon="menu" on-tap="{{togglePanel}}"></core-icon-button>
