### ISSUE TITLE
HTMLImports added in code view are not preserved when switching to design view

### ISSUE THREAD

**Issue by sorvell** [Polymer/designer#46]
Currently we strip out the HTMLImports in the code view and re-generate them from the designed elements. This is done to simplify the management of html imports for elements used in the designer. In order to preserve user imports, we need to either make imports handling more sophisticated or perhaps mark a section in the code output as `designer-generated`.

**Comment by MrWeb** [comment]
Hi, any news on this? (Code can't be saved, and basically the App itself stops working...)

**Comment by justinfagnani** [comment]
We're not working on this branch anymore. In master we don't rewrite the imports, so user imports will be preserved.
