### ISSUE TITLE
Load/save plugin architecture?

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/designer#78]
We replaced the save to/load from Gist with a connection to our backend. It was no big issue, but required several code changes.

I'm now wondering if there are any plans to add some kind of plugin architecture allowing to easily replace to save/load components?

**Comment by novasl** [comment]
I'm working on a project where we need to be totally decoupled from github/gist.
Could you please provide some help on how to go about doing it.

Many Thanks
