### ISSUE TITLE
add access to all icons sets

### ISSUE THREAD

**Issue by Quentigus** [Polymer/designer#91]
Hi !

Many icons sets are unavailable into the designer.

For exemple, those sets :
- device
- communication

All sets are listed here : http://www.polymer-project.org/components/core-icons/demo.html

**Comment by PremananthBanusekaran** [comment]
There are no icon sets listed in the link mentioned above. It shows server not found. 
Is there any other link to show icon set?

**Comment by Quentigus** [comment]
Here : https://www.polymer-project.org/0.5/components/core-icons/demo.html

**Comment by justinfagnani** [comment]
FYI, Designer 2 will allow users to add their own element and icon sets.
