### ISSUE TITLE
core-item exposes textContent but not label -- intentional?

### ISSUE THREAD

**Issue by kenmoore** [Polymer/designer#92]
I'm working along with Rob on the content in his talk from April where he's using Designer to set up a simple core-scaffold:
   http://youtu.be/mN7IAaRdi_k?t=3h3m47s

There the core-items in the menu have the label property exposed for easy editing.  In today's designer the label property isn't exposed, rather a textContent property is present which almost does what I want but appends the text to the existing "Item 1" label.

I'd like to see something more like this: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by whelks-chance** [comment]
Not sure what the video was for, but the issue remains that the label and textContent is muddled in the designer.
